### PR TITLE
Adding a (WIP) riscv32i model

### PR DESCRIPTION
**Pull request by onsdagens**
`` cargo run --example riscv `` in the riscv dir initializes the model with some sample instructions, there are multiple commented blocks of instructions in the example, so give them a go or write your own program!

The components are only implemented for vizia for now.

All of the riscv32i instructions except SYSTEM and MISC-MEM (so FENCE, FENCE.I and CSR ops) are implemented.

TODO: 

- [ ] Some sort of README
- [x] Proper tests
- [ ] Finish implementing the CSR component
- [ ] The data/instruction memory interfaces will probably end up changing to use a single address space
- [ ] Simple MMIO
- [ ] Interrupt controller (CLIC)
- [ ] With an interrupt controller, currently panicking code paths need to raise an exception instead
- [ ] The GUI needs a LOT of love
- [ ] EGui components

### CODE REVIEW

**Comment by onsdagens** [comment]
I missed the Signal format having changed, so while porting the RISC-V components to use the old Signal enum, i broke everything. I'll get to fixing it tomorrow.

**Comment by onsdagens** [comment]
I've ported the RISC-V components and some of the generic ones to use the new Signal implementation now. Also added some traces (these still need more work) and a separate ``fern_setup()`` that only shows component traces to make it easier to see what the actual model is doing.

**Comment by onsdagens** [comment]
Unit tests are now added, i tried touching each instruction so it ended up being a lot, especially in the decoder.

**Comment by onsdagens** [comment]
The ``riscv`` example now compiles ``asm.s``, links it using ``memory.x``, and initializes the instruction memory using the resulting ELF file. This makes ``riscv-gnu-toolchain`` a hard dependency. Eventually i'll roll it back to just taking an ELF file, but for playing around with in development i think this is nice for ergonomics.

**Comment by onsdagens** [comment]
Data memory is now also initialized according to ELF contents.

**Review by perlindgren — APPROVED** [review]
Let's go

**Pull request merged**
