### PR TITLE
add cache to improve build action time

### PR DESCRIPTION
**Pull request by onsdagens**
cuts build job time to 1.5-2 minutes

### CODE REVIEW

**Review by perlindgren — CHANGES_REQUESTED** [review]
Maybe leave a note in the CHANGELOG.md.

Also maybe add a GITHUB.md explaining how the (current) workflow is structured. I was trying to digest it, but its hard without any comments.

**Comment by onsdagens** [comment]
I removed the upload-artifact part of the workflow it uploads the built syncrim binary at the end of the workflow, but the first thing the workflow does when re-ran is cargo build, which rebuilds that same binary anyway...

**Comment by onsdagens** [comment]
Also removed the explicit clippy install, since clippy is included in the rust toolchain installed earlier.

**Review by perlindgren — APPROVED** [review]
Looks great, lets merge and see how fast the CI gets!!!

**Pull request merged**
